// <auto-generated />
using Lab_2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab_2.Migrations
{
    [DbContext(typeof(Lab_2Context))]
    [Migration("20220418060256_InverseProperty")]
    partial class InverseProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lab_2.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CurrentRoomId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("PreviousRoomId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Lab_2.Models.Room", b =>
                {
                    b.Property<int>("RoomNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomNumber"), 1L, 1);

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentClientId")
                        .HasColumnType("int");

                    b.Property<int>("PreviousClientId")
                        .HasColumnType("int");

                    b.Property<int>("Section")
                        .HasColumnType("int");

                    b.HasKey("RoomNumber");

                    b.HasIndex("CurrentClientId")
                        .IsUnique();

                    b.HasIndex("PreviousClientId")
                        .IsUnique();

                    b.ToTable("Room");
                });

            modelBuilder.Entity("Lab_2.Models.Room", b =>
                {
                    b.HasOne("Lab_2.Models.Client", "CurrentClient")
                        .WithOne("CurrentRoom")
                        .HasForeignKey("Lab_2.Models.Room", "CurrentClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab_2.Models.Client", "PreviousClient")
                        .WithOne("PreviousRoom")
                        .HasForeignKey("Lab_2.Models.Room", "PreviousClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentClient");

                    b.Navigation("PreviousClient");
                });

            modelBuilder.Entity("Lab_2.Models.Client", b =>
                {
                    b.Navigation("CurrentRoom")
                        .IsRequired();

                    b.Navigation("PreviousRoom")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
